apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - image: wordpress:4.8-apache
        name: wordpress
        env:
        - name: WORDPRESS_DB_HOST
          value: database-1.cu76kmobl9tm.ap-southeast-1.rds.amazonaws.com
        - name: WORDPRESS_DB_USER
          value: admin
        - name: WORDPRESS_DB_PASSWORD
          value: admin098
        - name: WORDPRESS_DB_NAME
          value: wordpress
        volumeMounts:
          - name: pv-wordpress-storage
            mountPath: /var/www/html
        ports:
        - containerPort: 80
      volumes:
        - name: pv-wordpress-storage
          persistentVolumeClaim:
            claimName: pvc-wordpress

---
apiVersion: v1
kind: Service
metadata:
  name: wordpress-service
spec:
  selector:
    app: wordpress
  ports:
  - port: 8030
    targetPort: 80

