apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-wordpress
spec:
  storageClassName: ""
  volumeName: pv-sp3
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteOnce
